[settings]
  ID = "cncf-contribute-contributors"

[build]
  base = "/"
  publish = "public"
  command = "go run mage.go -v Deploy"

[build.environment]
  HUGO_VERSION = "0.79.0"
  HUGO_ENV = "production"

[context.branch-deploy]
  command = "go run mage.go -v DeployPreview"
  
[context.deploy-preview]
  command = "go run mage.go -v DeployPreview"
